let CapybaraFiles = new Map()

CapybaraFiles.set(0, {name: 'Capybara-agresiva.png', url: "https://i.imgur.com/dFFZxau.png"})
CapybaraFiles.set(1, {name: 'Capybara-cantareta.png', url: "https://i.imgur.com/382O6br.png"})
CapybaraFiles.set(2, {name: 'Capybara-la-strand.png', url: "https://i.imgur.com/GB56xH9.png"})
CapybaraFiles.set(3, {name: 'Capybara-erbivora.png', url: "https://i.imgur.com/sPSBrhm.png"})
CapybaraFiles.set(4, {name: 'Capybara-cu-palarie.png', url: "https://i.imgur.com/cw9B9uC.png"})
CapybaraFiles.set(5, {name: 'Capybara-fericita.png', url: "https://i.imgur.com/wwHXJO8.png"})
CapybaraFiles.set(6, {name: 'Capybara-furioasa.png', url: "https://i.imgur.com/o7dC7x4.png"})
CapybaraFiles.set(7, {name: 'Capybara-girafa.png', url: "https://i.imgur.com/3NW0WsT.png"})
CapybaraFiles.set(8, {name: 'Capybara-inotatoare.png', url: "https://i.imgur.com/yLhHbim.png"})
CapybaraFiles.set(9, {name: 'Capybara-somnoroasa.png', url: "https://i.imgur.com/Uub4gSe.png"})
CapybaraFiles.set(10, {name: 'Capybara-de-cartier.png', url: "https://i.imgur.com/YQRaatb.png"})
CapybaraFiles.set(11, {name: 'Capybara-st-patrick.png', url: "https://i.imgur.com/VHb4qCm.png"})
CapybaraFiles.set(12, {name: 'Capybara-elena-luminita.png', url: "https://i.imgur.com/efSO8sC.png"})
CapybaraFiles.set(13, {name: 'Capybara-salam.png', url: "https://i.imgur.com/CCAlLZe.png"})
CapybaraFiles.set(14, {name: 'Capybara-micuta.png', url: "https://i.imgur.com/GwaxfgR.png"})
CapybaraFiles.set(15, {name: 'Capybara-hipster.png', url: "https://i.imgur.com/koUNazQ.png"})
CapybaraFiles.set(16, {name: 'Maki-bara.png', url: "https://i.imgur.com/wTLYHS1.png"})
CapybaraFiles.set(17, {name: 'Capybara-fotomodel.png', url: "https://i.imgur.com/ZcEEuCy.png"})
CapybaraFiles.set(18, {name: 'Capybara-corporatista.png', url: "https://i.imgur.com/4MwWQ5z.png"})
CapybaraFiles.set(19, {name: 'Capybara-soferita.png', url: "https://i.imgur.com/f79SErH.png"})
CapybaraFiles.set(20, {name: 'Capybara-florareasa.png', url: "https://i.imgur.com/K8kM89X.png"})
CapybaraFiles.set(21, {name: 'Capybara-frezata.png', url: "https://i.imgur.com/GnG2kwj.png"})
CapybaraFiles.set(22, {name: 'Capybara-la-SPA.png', url: "https://i.imgur.com/VU1OPkc.png"})
CapybaraFiles.set(23, {name: 'Super-capybara.png', url: "https://i.imgur.com/kWTarfx.png"})
CapybaraFiles.set(24, {name: 'Tank-ybara.png', url: "https://i.imgur.com/M3clAQz.png"})
CapybaraFiles.set(25, {name: 'Capybara-covidata.png', url: "https://i.imgur.com/TkrSVvu.png"})
CapybaraFiles.set(26, {name: 'Capybara-de-pe-targu-ocna.png', url: "https://i.imgur.com/SphZXN8.png"})
CapybaraFiles.set(27, {name: 'Capybara-distrasa.png', url: "https://i.imgur.com/eTTCscV.png"})
CapybaraFiles.set(28, {name: 'Capybara-fac-capybara.png', url: "https://i.imgur.com/gCFTgma.png"})
CapybaraFiles.set(29, {name: 'Capybara-sare-de-pe-pod.png', url: "https://i.imgur.com/u2Xw8Wh.png"})
CapybaraFiles.set(30, {name: 'M-am-capybara-pe-mine.png', url: "https://i.imgur.com/MW1ezK5.png"})
CapybaraFiles.set(31, {name: 'Salt-capybara.png', url: "https://i.imgur.com/TkrSVvu.png"})

module.exports.CapybaraFiles = CapybaraFiles